"""Canonical and RL-ready schema definitions for the Video RL dataset."""

from schema.canonical import (
    SubCapability,
    TaskType,
    BuildType,
    VideoURL,
    MessageContent,
    Message,
    Grader,
    ModalityProfile,
    VideoProfile,
    Evidence,
    Perturbation,
    BuildInfo,
    DataInfo,
    RewardInfo,
    SamplingInfo,
    QualityInfo,
    DecodePolicy,
    ExtraInfo,
    CanonicalSample,
)

__all__ = [
    "SubCapability",
    "TaskType",
    "BuildType",
    "VideoURL",
    "MessageContent",
    "Message",
    "Grader",
    "ModalityProfile",
    "VideoProfile",
    "Evidence",
    "Perturbation",
    "BuildInfo",
    "DataInfo",
    "RewardInfo",
    "SamplingInfo",
    "QualityInfo",
    "DecodePolicy",
    "ExtraInfo",
    "CanonicalSample",
]
